### ISSUE TITLE
Master Kontainer

### ISSUE THREAD

**Issue by dedyrosyadi** [vision-studio/sinarmas#22]
@muslih 

Kalau nomor kontainer sudah pernah dibuat maka user tidak bisa lagi create dengan nomor kontainer yang sama 

![image](https://user-images.githubusercontent.com/7915399/30527186-a4abd13c-9c58-11e7-99ba-fc43821bfd1f.png)

**Comment by muslih** [comment]
@dedyrosyadi issuenya kawa dipindahkan ke issue di repo `sinarmas-dev` lah, soalnya ini publik, lawan ngalih di refkan
