### ISSUE TITLE
Ubah desain dasbor

### ISSUE THREAD

**Issue by muslih** [vision-studio/sinarmas#4]
karena desain dasbor tidak update bootstrapnya, maka dirubah ke halaman dasbor yang baru

**Comment by muslih** [comment]
ini linknya bang @dedyrosyadi  https://medialoot.com/preview/frame/lumino.html

**Comment by dedyrosyadi** [comment]
theme sudah ane ganti 👯  @muslih

**Comment by muslih** [comment]
kamu keren kakak @dedyrosyadi , mun oke close aja issue nya bang

**Comment by dedyrosyadi** [comment]
ane close yes
