### ISSUE TITLE
UI pemilihan barang

### ISSUE THREAD

**Issue by muslih** [vision-studio/sinarmas#6]
list ui untuk pemilihan barang SPB (Surat Pengiriman Barang)

![1](https://user-images.githubusercontent.com/2532862/26982295-8ec61c52-4d6a-11e7-91f3-210b97602ce7.jpg)
![2](https://user-images.githubusercontent.com/2532862/26982296-8ec7f61c-4d6a-11e7-9d22-5344ca47b299.jpg)

data barang tampil pake modal

**Comment by dedyrosyadi** [comment]
interface pilih dengan modal

**Comment by dedyrosyadi** [comment]
close
