### ISSUE TITLE
Form Pengiriman

### ISSUE THREAD

**Issue by dedyrosyadi** [vision-studio/sinarmas#7]
- [x] modal not working, error : $(...)modal is not a function 
- [ ] select date not working, jd ane ganti pakai input text biasa aja dulu 

@muslih

**Comment by muslih** [comment]
foto bang @dedyrosyadi

**Comment by dedyrosyadi** [comment]
![image](https://user-images.githubusercontent.com/7915399/27012611-7618e2e2-4f05-11e7-811a-46138dc8587b.png)

**Comment by muslih** [comment]
done, tedobel imak meandak bootstrap filenya, cek di log diff @dedyrosyadi

**Comment by muslih** [comment]
@dedyrosyadi select date pindah ke issue hanyar aja
